### ISSUE TITLE
Support TS in sdk

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/generator-react-sdk#3]
#### Reason/Context

As in title. Support TS in react-sdk. It should be done at this same moment next to https://github.com/asyncapi/generator/issues/455

#### Description

It need to be use the official TS Rollup plugin https://github.com/rollup/plugins/tree/master/packages/typescript

**Comment by Stmated** [comment]
@magicmatatjahu There is no way of doing this manually currently, right? Since I can't change what plugins are sent to the rollup invocation.
Is there actually any more work required than to just add the typescript plugin along with the babel one?

Or even better, is there a way to disable rollup? Things seemed to work just fine for me, running it all through ts-node, but now rollup can't include my .ts-files.

**Comment by jonaslagoni** [comment]
@Stmated theoretically you could do your own pre-transpilation process. i.e. keep the template files under a different folder and then add your own transpiler process and output it to the `template` folder. Havent tested it but it should be possible until this issue is resolved.

Also if you feel the need for the option to disable the entire transpilation process feel free to create an issue with the use-case 😄

**Comment by magicmatatjahu** [comment]
> Is there actually any more work required than to just add the typescript plugin along with the babel one?

We wanted add TS supports in first `0.1.0` version, but we realized that we don't have a TS integration inside generator, so we avoided it, but yes, in `sdk` there is only needed add rollup plugin for TypeScript. 

And as @jonaslagoni wrote, at the moment you can write template in separate folder (e.g. `templateTS`) and check in `tsconfig.json` as output dir `template` and then run generator.

> Or even better, is there a way to disable rollup? Things seemed to work just fine for me, running it all through ts-node, but now rollup can't include my .ts-files.

Rollup is needed for simplify template code and transform `ESmodules` to `CommonJS` modules. Of course if you want use `sdk` as a standalone package, then you can use it without worrying about the rollup. Rollup is for Generator itself.

**Comment by magicmatatjahu** [comment]
Supporting TS has a one (for me huge) problem -> https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544 TS always complains about returned string from components:

```tsx
function Component() {
  return "foobar";
}

function App() {
  return (
    <Component /> // error JSX element type 'string' is not a constructor function for JSX elements.
  );
}
```

So we must wrap string to fragment like `<>foobar</>`. @jonaslagoni Can we accept this solution or wait for fixing typings? As you see issue is opened in 2017 year, so I think that it won't be fixed quickly.

**Comment by magicmatatjahu** [comment]
`selectively exclude errors/warnings from react` is not that easy 😄 We can make wrapper for string, but then it will be more difficult to use than using fragments `<></>`

**Comment by magicmatatjahu** [comment]
Still relevant, but we must handle that problem https://github.com/asyncapi/generator-react-sdk/issues/3#issuecomment-828299626

**Comment by sandrokeil** [comment]
> Supporting TS has a one (for me huge) problem -> [DefinitelyTyped/DefinitelyTyped#20544](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544) TS always complains about returned string from components:
> 
> ```tsx
> function Component() {
>   return "foobar";
> }
> 
> function App() {
>   return (
>     <Component /> // error JSX element type 'string' is not a constructor function for JSX elements.
>   );
> }
> ```
> 
> So we must wrap string to fragment like `<>foobar</>`. @jonaslagoni Can we accept this solution or wait for fixing typings? As you see issue is opened in 2017 year, so I think that it won't be fixed quickly.

Is this still a problem, because there exists a [`Text` component](https://github.com/asyncapi/generator-react-sdk/blob/master/src/components/Text.tsx). It is also possible to use [this workaround](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/20544#issuecomment-638661565) if still needed.

````tsx
import React, { ReactElement } from 'react'

function Component() {
   return ("foobar" as unknown) as ReactElement
}

function App() {
  return (
    <Component /> // no error
  );
```

**Comment by Reecer9714** [comment]
Something that may help is adding `children` to the following type definition
``` ts
export declare type PropsWithChildrenContent<P> = P & {
    children?: ReactNode;
    childrenContent?: string;
};
```
